### ISSUE TITLE
Milestone 3 Tasks

### ISSUE THREAD

**Issue by elabandari** [UBC-MDS/dsci-532-group-02-R#2]
Repo:  
- [x] 1. Create a new github.com repo for your dashr project
- [x] 2. Copy over your contributing guidelines, code of conduct README file, and the necessary data files.
- [ ] 3. Update README with a link to the deployed R dashboard and a new image/gif of the R dashboard in action.

Deployment on Heroku:
- [ ] 4. Deploy your app on Heroku and include the link to your deployed dashboard clearly visible near the top of your README.

App:
- [x] 5. Re-create histograms with ggplotly  
- [x] 6. Address TA feedback from Milestone 1

Reflection (in doc/reflection-milestone3.md):
- [x] 7. Document what has been implement/not-implemented. Include brief thoughts on the experience of implementing the dashboard a second time in another language. Mention feedback received and how that has impacted future planning. 300-400 words.

Give Peer Feedback (Optional):
- [x] 8. Give peer feedback to group 3. 

Canvas Submission:
- [ ] 9. `canvas-submission.html` (include link to peer feedback).

**Comment by rainbowxyt0305** [comment]
Repo:  
- [x] 1. Create a new github.com repo for your dashr project
- [x] 2. Copy over your contributing guidelines, code of conduct README file, and the necessary data files.
- [ ] 3. Update README with a link to the deployed R dashboard and a new image/gif of the R dashboard in action.

Deployment on Heroku:
- [ ] 4. Deploy your app on Heroku and include the link to your deployed dashboard clearly visible near the top of your README.

App:
- [x] 5. Re-create histograms with ggplotly  
- [x] 6. Address TA feedback from Milestone 1 with a `new issue` linked to TA's issue

Reflection (in doc/reflection-milestone3.md):
- [x] 7. Document what has been implement/not-implemented. Include brief thoughts on the experience of implementing the dashboard a second time in another language. Mention feedback received and how that has impacted future planning. 300-400 words.

Give Peer Feedback (Optional):
- [x] 8. Give peer feedback to group 3. 

Canvas Submission:
- [ ] 9. `canvas-submission.html` (include link to peer feedback).

**Comment by elina-linglin** [comment]
Give Peer Feedback (Optional):
- [x] 8. Give peer feedback to group 3. 
Link: https://github.com/UBC-MDS/dsci532-group3/issues/45
